
name = "senterosai-chat"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[[build.upload]]
format = "directory"
dir = "dist"

[env.production]
name = "senterosai-chat-prod"

[vars]
NODE_ENV = "production"
